# Generated by Django 5.1.7 on 2025-03-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_name_users_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('user_id', models.IntegerField()),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('profile_photo', models.ImageField(upload_to='profile_photos/')),
                ('aadhaar_card', models.ImageField(upload_to='aadhaar_cards/')),
                ('pan_card', models.ImageField(upload_to='pan_cards/')),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=63)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
