# Generated by Django 5.1.7 on 2025-03-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_token_user_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhaar_card',
            field=models.ImageField(null=True, upload_to='aadhaar_cards/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pan_card',
            field=models.ImageField(null=True, upload_to='pan_cards/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
