# Generated by Django 5.1.7 on 2025-05-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_aadhaar_card_alter_user_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aadhaar_card',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pan_card',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='user',
            name='aadhaar_card_file_url',
            field=models.FileField(null=True, upload_to='aadhaar_card_upload_path'),
        ),
        migrations.AddField(
            model_name='user',
            name='aadhaar_card_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pan_card_file_url',
            field=models.FileField(null=True, upload_to='pan_card_upload_path'),
        ),
        migrations.AddField(
            model_name='user',
            name='pan_card_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo_file_url',
            field=models.FileField(null=True, upload_to='profile_photo_upload_path'),
        ),
    ]
