# Generated by Django 5.1.7 on 2025-05-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_aadhaar_card_remove_user_pan_card_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_photo_file_url',
        ),
        migrations.AddField(
            model_name='user',
            name='_10th_certificate_file_url',
            field=models.FileField(null=True, upload_to='_10th_certificate_upload_path'),
        ),
        migrations.AddField(
            model_name='user',
            name='_10th_certificate_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='_12th_certificate_file_url',
            field=models.FileField(null=True, upload_to='_12th_certificate_upload_path'),
        ),
        migrations.AddField(
            model_name='user',
            name='_12th_certificate_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dateofbirth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='graduation_certificate_file_url',
            field=models.FileField(null=True, upload_to='graduation_certificate_upload_path'),
        ),
        migrations.AddField(
            model_name='user',
            name='graduation_certificate_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_size_photo_file_url',
            field=models.FileField(null=True, upload_to='passport_size_photo_upload_path'),
        ),
        migrations.AddField(
            model_name='user',
            name='signature_file_url',
            field=models.FileField(null=True, upload_to='signature_upload_path'),
        ),
    ]
