# Generated by Django 5.1.7 on 2025-05-13 19:03

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_username_user_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_10th_certificate_file_url',
            field=models.FileField(null=True, storage='string', upload_to=users.models._10th_certificate_upload_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='_12th_certificate_file_url',
            field=models.FileField(null=True, storage='string', upload_to=users.models._12th_certificate_upload_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='aadhaar_card_file_url',
            field=models.FileField(null=True, storage='string', upload_to=users.models.aadhaar_card_upload_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='graduation_certificate_file_url',
            field=models.FileField(null=True, storage='string', upload_to=users.models.graduation_certificate_upload_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='pan_card_file_url',
            field=models.FileField(null=True, storage='string', upload_to=users.models.pan_card_upload_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_size_photo_file_url',
            field=models.FileField(null=True, storage='string', upload_to=users.models.passport_size_photo_upload_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='signature_file_url',
            field=models.FileField(null=True, storage='string', upload_to=users.models.signature_upload_path),
        ),
    ]
