# Generated by Django 5.1.7 on 2025-06-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='_10th_certificate_file_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='_10th_certificate_text',
        ),
        migrations.RemoveField(
            model_name='user',
            name='_12th_certificate_file_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='_12th_certificate_text',
        ),
        migrations.RemoveField(
            model_name='user',
            name='aadhaar_card_file_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='aadhaar_card_text',
        ),
        migrations.RemoveField(
            model_name='user',
            name='graduation_certificate_file_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='graduation_certificate_text',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pan_card_file_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pan_card_text',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passport_size_photo_file_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='signature_file_url',
        ),
        migrations.AddField(
            model_name='user',
            name='document_texts',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='document_urls',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
