# Generated by Django 5.1.7 on 2025-06-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user__10th_certificate_file_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fullname',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='permanentAddress',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.AddField(
            model_name='user',
            name='alt_phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('Select', 'Select'), ('GEN', 'GEN'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS')], default='Select', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='correspondenceAddress',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='disability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='domicileState',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fathersName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Select', 'Select'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Select', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='maritalStatus',
            field=models.CharField(choices=[('Select', 'Select'), ('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Others', 'Others')], default='Select', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='mothersName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='religion',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
