# Generated by Django 5.1.7 on 2025-06-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_fullname_user_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
