# Generated by Django 5.1.7 on 2025-06-24 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_district_user_mandal_user_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_email', models.EmailField(max_length=254)),
                ('share_token', models.CharField(max_length=100, unique=True)),
                ('shared_personal_data', models.JSONField(blank=True, null=True)),
                ('shared_document_urls', models.JSONField(blank=True, null=True)),
                ('shared_document_texts', models.JSONField(blank=True, null=True)),
                ('include_documents', models.BooleanField(default=True)),
                ('include_ocr_text', models.BooleanField(default=True)),
                ('include_personal_info', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('receiver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_shares', to='users.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_shares', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='SharedDataUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('form_url', models.URLField(blank=True, null=True)),
                ('fields_used', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('shared_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='users.sharedprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('share_request', 'Share Request'), ('share_accepted', 'Share Accepted'), ('share_declined', 'Share Declined'), ('share_revoked', 'Share Revoked'), ('share_used', 'Share Used')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.user')),
                ('related_share', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sharedprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
