# Generated by Django 5.1.7 on 2025-06-25 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_sharedprofile_shareddatausage_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareddatausage',
            name='shared_profile',
        ),
        migrations.RemoveField(
            model_name='sharedprofile',
            name='receiver_user',
        ),
        migrations.RemoveField(
            model_name='sharedprofile',
            name='sender',
        ),
        migrations.CreateModel(
            name='DataShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(max_length=254)),
                ('receiver_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('stopped', 'Stopped')], default='pending', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('sender_email', 'receiver_email')},
            },
        ),
        migrations.CreateModel(
            name='ShareNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('notification_type', models.CharField(choices=[('share_request', 'Share Request'), ('share_accepted', 'Share Accepted'), ('share_declined', 'Share Declined'), ('share_stopped', 'Share Stopped')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.datashare')),
            ],
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='SharedDataUsage',
        ),
        migrations.DeleteModel(
            name='SharedProfile',
        ),
    ]
