# Generated by Django 5.1.7 on 2025-06-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_shareddatausage_shared_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datashare',
            name='shared_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
