# Generated by Django 5.2.2 on 2025-07-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_datashare_shared_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='datashare',
            name='selected_documents',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
