# Generated by Django 5.2.2 on 2025-07-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_datashare_selected_documents'),
        ('users', '0018_add_extra_details'),
    ]

    operations = [
    ]
