# Generated by Django 5.2.2 on 2025-07-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_contactusrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_doc_categories',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
