# Generated by Django 5.2.2 on 2025-07-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_custom_doc_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='changedNameDetail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hasChangedName',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='motherTongue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
