# Generated by Django 5.2.2 on 2025-07-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_referral_code_user_referred_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='highest_education',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Matriculation (10th)', 'Matriculation (10th)'), ('Higher Secondary (10+2)', 'Higher Secondary (10+2)'), ('Diploma', 'Diploma'), ('Graduation', 'Graduation'), ('Post Graduation', 'Post Graduation'), ('Ph.D', 'Ph.D')], max_length=32, null=True),
        ),
    ]
