# Generated by Django 5.2.2 on 2025-07-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_user_force_advanced_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_website_access',
            field=models.BooleanField(default=False, help_text='Enable access to the main application'),
        ),
        migrations.AddField(
            model_name='user',
            name='website_access_disabled_date',
            field=models.DateTimeField(blank=True, help_text='Date when access was disabled', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='website_access_enabled_date',
            field=models.DateTimeField(blank=True, help_text='Date when access was enabled', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='website_access_notes',
            field=models.TextField(blank=True, help_text="Admin notes about this user's access"),
        ),
    ]
