# Generated by Django 5.2.2 on 2025-07-16 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_user_has_website_access_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebsiteAccess',
        ),
    ]
