# Generated by Django 5.2.2 on 2025-07-16 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_delete_websiteaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='website_access_disabled_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='website_access_enabled_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='website_access_notes',
        ),
    ]
