# Generated by Django 5.2.2 on 2025-07-17 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_accesscontroller'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscontroller',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_controllers', to='users.user'),
        ),
    ]
