# Generated by Django 5.2.2 on 2025-07-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_accesscontroller_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscontroller',
            name='force_advanced_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accesscontroller',
            name='has_website_access',
            field=models.BooleanField(default=False),
        ),
    ]
