# Generated by Django 5.2.2 on 2025-07-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_accesscontroller_force_advanced_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscontroller',
            name='referral_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='accesscontroller',
            name='referred_by',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='accesscontroller',
            name='successful_referrals',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
