# Generated by Django 5.2.2 on 2025-07-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_accesscontroller_referral_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesscontroller',
            name='name',
        ),
    ]
