"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ynw%r6t5@)=uoz@os#k54f5tz(06w^5gr9)k95)ua3rdp1#a3k'
# AIVEN_SERVICE_PASSWORD= 'AVNS_ONEe9noXWfbeA_-Vjf3'
AIVEN_SERVICE_PASSWORD = os.getenv('AIVEN_SERVICE_PASSWORD')


# Google Drive Storage Settings
DROPBOX_ACCESS_TOKEN = 'sl.u.AFpiy_-ROkTEUEhfO0zIfBQIt1w47cjKYtVof4Ksvqv16UQ0YGZ0s1stoahQQxwcDrATpF67RD6xaOVtyO9HsdJxnY_2yWxBcrfQCa-f4801rptogBWMKMC1chVIpUMgaAqI2wWARB45wFJ07Bl1V6XLp9U8w95L45e_q1BSOK9g6uDeI09toCHRBLLLwjHmZ-yTjVu9tdqHWxQIRoIrP68o0q2W-uH96zONF4XyUkcVAATCgqq9eoITMwSNvJS5l_P5ueAyLbxwPhvhO-3FOKV3niO4R_kjgWKjPRIrMweLlb_j_lVnPh9YRa1MoRth2wqr3p-9xCVV9Zj3LH1YccK9KPAFasOzHezn4FlJvE3RQChnLcHnBwSyYURvF-1vhKlnTdwy8tD11A4s39DO-kdPAXzxV8Gi5n30WsAJlAqe0QkPVxxKfktPmoJ-qulmJkjEteJMGE8HGsYpU2kVYG72HVZDab2fjc1cAuS55ALcDAeDinVCOTFTcVwId20r0LxVuf2vzUfyuRbGtFJ4VeRDWof19zRKgIrqH8eSaAfg-bTpFxfEBzInUYXxYyaYzIDzT-zHbHyUea4sNfIKeWZGRh6heNvZjsOLkblhPbMBlpPIJZrIlaq-Bq8SmWzMo4Ig3OIEmGWHqVAIYFEpINCQu5rLp4VALEtvw3AC2Yf2gG9FQZAcuw3RYMcS8XcQOGu39k9Oleuc_rJJ1IV6EQm-lrihrcWZ-uTeNOabOASHdUQJtoUg1erhmC13geme1dkIaScQl8E9FJ8Gi--DovEjjhYUx9GyPOFUe9672WP_GCYmYgbA1OsvK6dP-1Ue7VXKsdoo7rcXaVKHj_rRfjgDuXzJX2_fGsO2BX1YmI3QDwagMWEa512n3xoWfiDGRK0OcNzHWSjI5hMmcrECd9113bxJCk2Xwye4nuo_22cbmeuc86Gj3-sPwKyesdbDfteNY6AdIhy7z7KofNwe2BUZ1GZPNvwmscEkizW34pphRzG9oRXRPIAZdFLWhjdNG-VVUJhQUJguM5Gg_oZgI4OoAT4GevVcaEz9pIM_B6wjw-AciJwQ2dfsr2dWG5ysBhasO42aVweajFpAUcV6IxAHqqoAYNW7WnR-Pi3sh9wzcc8i7HXYQN0jSArBtzkAMUxO-kusNTEkFP_pUhUYy3owE_rsqrJ3YxEY4tdqYsFhn3rvIkHgFoZ4mSsp9aUKixTa8gN8cy_gMb9RZy3KuivCMPSQBlYXxS-xy8l0-xF5P2ARu8HS3ERUm3aTltFeStkfdbHcW7RHjwARWcPEQmXnf0gT01U3D2ZxTmvEbTca2uGyvuQxJ94FH8MNcMcG42iEXHv3sm5F0OdJO-UBnNqXunNX8MBMeBWIJjkEXs0wIU7sI8c4n16Tui2SLxE8A7JnrvHqx73rYVYqzi6JAJ-1'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["sabapplier-ai-backend.onrender.com", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'defaultdb',
        'USER': 'avnadmin',
        'PASSWORD': AIVEN_SERVICE_PASSWORD,
        'HOST': 'test-pg0001-amgens-42ab.h.aivencloud.com',
        'PORT': '24554',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# White listing the localhost:3000 port
# for React
CORS_ORIGIN_WHITELIST = (
    # "https://holmes629.github.io/SabApplier-AI/",
    'http://localhost:3000',
)
CORS_ALLOWED_ORIGINS = [
    # "https://holmes629.github.io/SabApplier-AI/",
    "http://localhost:3000",  # Allow frontend to access backend
] 
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^chrome-extension://.+$",  # allow all extensions temporarily
    r"^http://localhost:.*$",    # if testing via localhost too
]

CORS_ALLOW_CREDENTIALS = True  # Allow cookies and authentication

CSRF_TRUSTED_ORIGINS = ["https://sabapplier-ai-backend.onrender.com/", "http://localhost:3000"]  # Prevent CSRF issues


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
