"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ynw%r6t5@)=uoz@os#k54f5tz(06w^5gr9)k95)ua3rdp1#a3k'
AIVEN_SERVICE_PASSWORD= 'AVNS_1YyoLCsZN4Ojj630rl4'
# AIVEN_SERVICE_PASSWORD = os.getenv('AIVEN_SERVICE_PASSWORD')


# Google Drive Storage Settings
# DROPBOX_ACCESS_TOKEN = os.getenv('DROPBOX_ACCESS_TOKEN')
DROPBOX_ACCESS_TOKEN = 'sl.u.AFpTWu_sMiM9hYzunJgbzRm4IXBPG5VD3vR5asrpYIj-pPXQecqkTvidLCeYU8KFe4qH3ucc4YHk7r5qUOx79evhH4Tw3JJTNA_HU_CDftk2SvwZ-_iPVPM_z1men6NBDtuyI6zdkmJ6dG7iMHohEKpjDJ5HOnuZAXRxY4sdvzi-Z6NfZqAjNPbc7QSW3G11ZW8PPlKxjuK9UqVRjGjJjxIPWPHMRmWWXc8Vm5PZzj0XzGFmzxFRJk3Xq6vE8jXcAjNLr-rKw5NIYYVBvrCmKGlu6PAnlEF-AohA5vdwveODGeb0C4QlX7ytDR3eYEv3qeIliSuWpVsaesEDyk4B2ewt1bKHUPi5Y76jd5usXk4eYjEzSvCysznvKWEh54scVnsHvAY_1GkXQa_2BRI4Mzst7F7Ag0mtsVmHCsFb1friNAJJh9wG8bGyTgGrl9uSRD2w5-G3KEZnJUwxWx0ofo5IcYwH8Z3w7Qqdddw9ArteXDHf3fC-ZtNwgmhvmw4aGkObP7a9TghudokRJJGIvycoCU5pKOvhRES-KXS-uSFm3PBB4QtIyeeaEUaD8w2wR249eL6PYF_ZyOtgSMsW-xTewluQ2PpSvch1gKNkV2XF7W8yWEfLlKJ8mQ11N8xce6YzphfUCOON337rGfxe_4WGwJj7f8oG7yZrShM1G7u9NxAAY6Uan1LTDUymHQApOA0KR38hggbWO0XvO01rQqMP9xZiaVEB4fnRVS9UW7wPSM_3VoQ6B-40j6v8SjJrb4ckYTmPvPPoJOqOSJpMLAVJY8Vh_zy4YTOpBivUVuvxqx0tUr3NsRUhvtd8KDio2xTLLHNqsom8qtjQ7WWIIHGHSi9um1W1OvDRIEwacuPdzq0ijRaZ1_oFdzzeVK2P9GJtWg4TPY0sWaf1Npe6KnPvFUZMohh8ZlF-6aT9a1jzthTMpXRWMruUGcFwPJCidRCNrRshob_7cn4JGlLduk0b6arRdgh-WcYEETDvNeC4FVpWoW-r6Lg02i0umrTsBz309H7fF3q0oUevtvvQtq2TezlTgQUmjK2MbQZ8OVpX2Q72dQ3rR_xcavzwTxq4UPxp66SQNcmPh7Ggz-uj4zHqWgaycfFDS1Fmx6-sgbiQJQb4v9JnCB_ljUgOleGQjQtBy8VgjByu6Ke8EQPfaZRDAamr8dFl2I_7Wi0B46X3ll7GzULD8gQlOk3bJ8ad0TDluVA2xasvHmmd2gtU-shzWEsPWCpQE1zZKHy4N1sv4GEBGYLz8uaO89s3qnZb28S-1Nk6GxeX_UUSZ1Hx7LwMiL-OxwwZ_ASTm1doX_o5BFvKgsOou3TFN6dAn-2zJDTvoF2Vb6Iq6-ZOwxXenXJQggD7z1hYjIidS1tYLtAHQNvhKxpsW6wxxHm_XYaxuwBagMm4VD1mi6SbXwlNlXwa'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["sabapplier-ai-backend.onrender.com", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'defaultdb',
        'USER': 'avnadmin',
        'PASSWORD': AIVEN_SERVICE_PASSWORD,
        'HOST': 'test-pg0001-amgens-42ab.h.aivencloud.com',
        'PORT': '24554',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# White listing the localhost:3000 port
# for React
CORS_ORIGIN_WHITELIST = (
    "https://holmes629.github.io/SabApplier-AI/",
    'http://localhost:3000',
)
CORS_ALLOWED_ORIGINS = [
    "https://holmes629.github.io/SabApplier-AI/",
    "http://localhost:3000",  # Allow frontend to access backend
] 
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^chrome-extension://.+$",  # allow all extensions temporarily
    r"^http://localhost:.*$",    # if testing via localhost too
]

CORS_ALLOW_CREDENTIALS = True  # Allow cookies and authentication

CSRF_TRUSTED_ORIGINS = ["https://sabapplier-ai-backend.onrender.com/", "http://localhost:3000"]  # Prevent CSRF issues


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
